UpliftStore/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UpliftStore.DataAccess.Data.Repository.Interfaces;
using UpliftStore.Utility;

namespace UpliftStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            if (!id.HasValue)
            {
                return View(new Models.Category());
            }

            var category = _unitOfWork.CategoryRepository.Get(id.GetValueOrDefault());
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Models.Category category)
        {
            if (ModelState.IsValid)
            {
                if (category.Id == 0)
                {
                    _unitOfWork.CategoryRepository.Add(category);
                }
                else
                {
                    _unitOfWork.CategoryRepository.Update(category);
                }

                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        #region API Calls

        [HttpGet("api/categories")]
        public IActionResult GetAll()
        {
            return new JsonResult(new 
            { 
                data = _unitOfWork.SP_Call.GetAll<Models.Category>(SD.USP_GetAllCategories)
            });
        }

        [HttpDelete("api/[controller]/{id}")]
        public IActionResult Delete(int id)
        {
            var category = _unitOfWork.CategoryRepository.Get(id);
            if (category == null)
            {
                return new JsonResult(new 
                { 
                    success = false, 
                    message = "Category was not found" 
                });
            }

            _unitOfWork.CategoryRepository.Remove(id);
            _unitOfWork.Save();

            return new JsonResult(new 
            { 
                success = true, 
                message = "Category deleted successfully" 
            });
        }

        #endregion
    }
}

UpliftStore/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UpliftStore.DataAccess.Data.Repository.Interfaces;
using UpliftStore.Models.ViewModels;
using UpliftStore.Utility;

namespace UpliftStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Index(string status)
        {
            ViewData["Status"] = status;

            return View();
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            OrderViewModel orderViewModel = new OrderViewModel
            {
                OrderHeader = _unitOfWork.OrderHeaderRepository.Get(id),
                OrderDetails = _unitOfWork.OrderDetailRepository.GetAll(filter: d => d.OrderHeaderId == id)
            };

            return View(orderViewModel);
        }

        [HttpGet]
        public IActionResult Approve(int id)
        {
            var orderHeader = _unitOfWork.OrderHeaderRepository.Get(id);
            if (orderHeader == null)
            {
                return NotFound();
            }

            _unitOfWork.OrderHeaderRepository.ChangeOrderStatus(id, SD.ApprovedStatus);

            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet]
        public IActionResult Reject(int id)
        {
            var orderHeader = _unitOfWork.OrderHeaderRepository.Get(id);
            if (orderHeader == null)
            {
                return NotFound();
            }

            _unitOfWork.OrderHeaderRepository.ChangeOrderStatus(id, SD.RejectedStatus);

            return RedirectToAction(nameof(Details), new { id });
        }

        #region API Calls

        [HttpGet("api/orders")]
        public IActionResult GetAll()
        {
            return new JsonResult(new
            {
                data = _unitOfWork.OrderHeaderRepository.GetAll()
            });
        }

        [HttpGet("api/orders/pending")]
        public IActionResult GetAllPending()
        {
            return new JsonResult(new
            {
                data = _unitOfWork.OrderHeaderRepository.GetAll(filter: oh => oh.Status == SD.SubmittedStatus)
            }); ;
        }

        [HttpGet("api/orders/approved")]
        public IActionResult GetAllApproved()
        {
            return new JsonResult(new
            {
                data = _unitOfWork.OrderHeaderRepository.GetAll(filter: oh => oh.Status == SD.ApprovedStatus)
            });
        }

        #endregion
    }
}

UpliftStore/Areas/Admin/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using UpliftStore.DataAccess.Data.Repository.Interfaces;
using UpliftStore.Models.ViewModels;

namespace UpliftStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ServiceController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        [BindProperty]
        public IFormFileCollection UploadImage { get; set; }

        public ServiceController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            ServiceViewModel serviceViewModel = new()
            {
                Service = new Models.Service(),
                Categories = _unitOfWork.CategoryRepository.GetCategoryListForDropDown(),
                Frequencies = _unitOfWork.FrequencyRepository.GetFrequencyListForDropDown()
            };

            if (id.HasValue)
            {
                serviceViewModel.Service = _unitOfWork.ServiceRepository.Get(id.GetValueOrDefault());
            }

            return View(serviceViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ServiceViewModel serviceViewModel)
        {
            if (ModelState.IsValid)
            {
                string webrootPath = _hostEnvironment.WebRootPath;

                if (serviceViewModel.Service.Id == 0)
                {
                    var fileName = UploadFile(webrootPath, UploadImage);
                    serviceViewModel.Service.ImageFile = fileName;

                    _unitOfWork.ServiceRepository.Add(serviceViewModel.Service);
                }
                else
                {
                    var service = _unitOfWork.ServiceRepository.Get(serviceViewModel.Service.Id);
                    if (UploadImage.Count > 0)
                    {
                        string imagePath = Path.Combine(webrootPath, "images", "services", service.ImageFile);

                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }

                        var fileName = UploadFile(webrootPath, UploadImage);

                        serviceViewModel.Service.ImageFile = fileName;
                    }
                    else
                    {
                        serviceViewModel.Service.ImageFile = service.ImageFile;
                    }

                    _unitOfWork.ServiceRepository.Update(serviceViewModel.Service);
                }

                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }

            return View(serviceViewModel);
        }

        #region API Calls

        [HttpGet("api/services")]
        public IActionResult GetAll()
        {
            return new JsonResult(new
            {
                data = _unitOfWork.ServiceRepository.GetAll(includeProperties: "Category,Frequency")
            });
        }

        [HttpDelete("api/[controller]/{id}")]
        public IActionResult Delete(int id)
        {
            try
            {
                var service = _unitOfWork.ServiceRepository.GetFirstOrDefault(s => s.Id == id);
                if (service == null)
                {
                    return new JsonResult(new
                    {
                        success = false,
                        message = "Error while deleting"
                    });
                }

                var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "images", "services", service.ImageFile);
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }

                _unitOfWork.ServiceRepository.Remove(service);
                _unitOfWork.Save();

                return new JsonResult(new
                {
                    success = true,
                    message = "Delete successful"
                });
            }
            catch (Exception)
            {
                return new JsonResult(new
                {
                    success = false,
                    message = "An exception occurred while deleting"
                });
            }
        }

        #endregion

        #region Private Methods

        private string UploadFile(string webrootPath, IFormFileCollection files)
        {
            string uploadPath = Path.Combine(webrootPath, "images", "services");
            string extension = Path.GetExtension(files[0].FileName);
            string fileName = Guid.NewGuid() + extension;

            using (var fileStream = new FileStream(Path.Combine(uploadPath, fileName), FileMode.Create))
            {
                files[0].CopyTo(fileStream);
            }

            return fileName;
        }

        #endregion
    }
}

UpliftStore/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using UpliftStore.DataAccess.Data.Repository.Interfaces;
using UpliftStore.Utility;

namespace UpliftStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Admin)]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public UserController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var users = _unitOfWork.UserRepository.GetAll(u => u.Id != claims.Value);

            return View(users);
        }

        [HttpGet]
        public IActionResult Lock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _unitOfWork.UserRepository.LockUser(id);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Unlock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _unitOfWork.UserRepository.UnlockUser(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

UpliftStore/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to list</a>
    </div>
    <div class="col">
        <button type="submit" id="btnCreateElement" class="btn btn-primary form-control">Create</button>
    </div>
</div>

UpliftStore/Views/Shared/_EditAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to list</a>
    </div>
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Edit</button>
    </div>
</div>

UpliftStore/Views/Shared/_Layout.cshtml
@using UpliftStore.Utility
@using UpliftStore.Extensions
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor httpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UpliftStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" />
</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-info mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">Uplift Store</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav mr-auto">
                        @if (User.IsInRole(SD.Manager) || User.IsInRole(SD.Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu bg-info" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-white" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item text-white" asp-area="Admin" asp-controller="Frequency" asp-action="Index">Frequency</a>
                                    <a class="dropdown-item text-white" asp-area="Admin" asp-controller="Service" asp-action="Index">Service</a>
                                    <a class="dropdown-item text-white" asp-area="Admin" asp-controller="WebImage" asp-action="Index">Image</a>
                                    
                                    @if (User.IsInRole(SD.Admin))
                                    {
                                        <a class="dropdown-item text-white" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>
                                    }

                                    <a class="dropdown-item text-white" asp-area="Admin" asp-controller="Order" asp-action="Index">Order</a>
                                </div>
                            </li>
                        }

                        @{ 
                            var cartItemIds = httpContextAccessor.HttpContext.Session.GetObject<List<int>>(SD.SessionCart);
                        }

                        @if (cartItemIds != null)
                        {
                            <li class="nav-item">
                                <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link text-white">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@cartItemIds.Count)
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a href="#" class="nav-link text-white">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                </a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_CookieConsentPartial" />
        </main>
    </div>

    <footer class="border-top footer bg-info text-white">
        <div class="container">
            &copy; @DateTime.Now.Year - UpliftStore
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/3.1.1/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.6.2/tinymce.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>